name: trendmate
description: TrendMate's App

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  intl: ^0.17.0

  # UI
  cached_network_image: ^3.1.0

  # DB

  # firebase
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.3

  # services
  provider: ^6.0.0
  url_launcher: ^6.0.11

  # utils
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  dart_code_metrics: ^4.3.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "fastlane/metadata/android/en-US/images/icon.png"

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

  uses-material-design: true

assets: